[project]
authors = ["Erik Tollerud <erik.tollerud@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hthv4_logo3d"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
build123d = ">=0.7.0,<0.8"

[pypi-dependencies]
ocp-vscode = ">=2.6.1, <3"
