[project]
authors = ["Erik Tollerud <erik.tollerud@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hthv4_logo3d"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
build123d = ">=0.7.0,<0.8"
pytorch = ">=2.5.1,<3"
timm = "==0.6.7"
torchvision = ">=0.20.1,<0.21"
jupyterlab = ">=4.3.1,<5"
tqdm = ">=4.67.0,<5"
matplotlib = ">=3.9.1,<4"

[pypi-dependencies]
ocp-vscode = ">=2.6.1, <3"
